FROM python:3.11.13-slim-bookworm@sha256:86adf8dbadc3d6e82ee5dd2c74bec2e1c2467cdad47886280501df722372d2e1
RUN pip install --no-cache-dir cassandra-driver==3.29.2
WORKDIR /work
CMD ["sleep", "infinity"]
